version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday" # Korrigiert: Wochentag als Text
      time: "00:05"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 15
    assignees:
      - hualex70
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday" # Korrigiert: Wochentag als Text
      time: "00:05"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 15
    assignees:
      - hualex70