name: Automerge Dependabot

on:
  pull_request:
    types: [opened, reopened, synchronized]

permissions:
  pull_requests: write
  contents: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Fetch Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v3
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Automerge PR
        uses: iobroker-bot-orga/action-automerge-dependabot@v1
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"